### ISSUE TITLE
Sim doesn't open IE

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/number-line-integers#54] opened 2019-11-13 23:17 UTC
**Test device**
Windows 7 device
**Operating System**
Windows 7 6.1
**Browser**
Internet Explorer
**Problem description**
From https://github.com/phetsims/QA/issues/457

Fails to open in IE, similar to other recent fail to load issues

Console Error:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: number-line-integers_en_phet.html
HTML1300: Navigation occurred.
File: number-line-integers_en_phet.html
warning: no support for Web Audio detected, using stubbed audio context
SCRIPT438: Object doesn't support property or method 'from'
File: number-line-integers_en_phet.html, Line: 1102, Column: 148

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.9/phet/number-line-integers_en_phet.html
Version: 1.0.0-dev.9 2019-11-13 22:18:32 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1366x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment] 2019-11-14 17:36
This is already identified as a general problem with the build process in https://github.com/phetsims/perennial/issues/153.  I am going to mark it as "blocks publication" but will also unassign it, since there is nothing I can do in the sim code itself.  This will remind me to double check that the problem is resolved before publishing.

**Comment by zepumph** [comment] 2019-11-14 21:26
This should now be fixed because of commits in https://github.com/phetsims/chipper/issues/817. Please confirm and close if all is good.

**Comment by jbphet** [comment] 2019-11-15 20:48
Yep, I just built a version and it ran fine in IE.  Thanks @zepumph.  Closing.

**Closed as completed by jbphet** 2019-11-15 20:48 UTC
Labels: type:bug, status:blocks-sim-publication
