### ISSUE TITLE
Labels overlap when the piggy banks are close to each other

### ISSUE THREAD

**Issue by megan-phet** [phetsims/number-line-integers#58] opened 2019-11-14 19:04 UTC
<b>Test Device</b>
- MacBook Pro

<b>Operating System</b>
- MacOS 10.15.1

<b>Browser</b>
- All latest

<b>Problem Description</b>
For phetsims/QA#457
Labels will overlap when the two piggybanks are close to each other. 

<b>Visuals</b>
<img width="255" alt="Screen Shot 2019-11-14 at 12 03 43 PM" src="https://user-images.githubusercontent.com/40698031/68887895-13508200-06d7-11ea-9c16-f5de1541c090.png">             <img width="151" alt="Screen Shot 2019-11-14 at 12 10 58 PM" src="https://user-images.githubusercontent.com/40698031/68888271-d638bf80-06d7-11ea-984e-ceadad2c2e28.png">

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Line: Integers‬
URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.9/phet/number-line-integers_en_phet.html
Version: 1.0.0-dev.9 2019-11-13 22:18:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Language: en-US
Window: 1129x733
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment] 2019-11-15 17:50
This is by design.  Closing.

**Closed as completed by jbphet** 2019-11-15 17:50 UTC
Labels: type:bug
